# Generated by Django 4.2.2 on 2023-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbHousingComplexes',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('complex_name', models.TextField(unique=True)),
                ('street_address', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'tb_housing_complexes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLeases',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('lease_start', models.TextField()),
                ('lease_end', models.TextField()),
                ('created_date', models.TextField()),
            ],
            options={
                'db_table': 'tb_leases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbResidentInfo',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('phone', models.TextField(unique=True)),
                ('birthdate', models.TextField()),
                ('gender', models.TextField()),
            ],
            options={
                'db_table': 'tb_resident_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbStudentHousingUnits',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('unit_number', models.TextField()),
                ('gender', models.TextField()),
                ('room', models.TextField()),
                ('bed', models.TextField()),
                ('room_type', models.TextField()),
                ('rent_price', models.FloatField()),
            ],
            options={
                'db_table': 'tb_student_housing_units',
                'managed': False,
            },
        ),
    ]
